if(${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(_ZLIB_PREFIX "${CMAKE_CURRENT_LIST_DIR}/zlib/build64")
else()
	set(_ZLIB_PREFIX "${CMAKE_CURRENT_LIST_DIR}/zlib/build32")
endif()
set(ZLIB_INCLUDE_DIR "${_ZLIB_PREFIX}/include")
set(ZLIB_LIBRARY "${_ZLIB_PREFIX}/Release/zlib.lib")
set(_ZLIB_PREFIX)
